version: '3.8'

services:
  app:
    image: phanindhrasura/php-app:latest  # replace with your actual Docker Hub image
    ports:
      - "9000:9000"
    volumes:
      - app_data:/var/www/html
    networks:
      - app_network
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/PHP/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_data:/var/www/html
    networks:
      - app_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - app_network
    depends_on:
      - mysql

volumes:
  db_data:
  app_data:

networks:
  app_network:
    driver: overlay
